"""crm extension tables and column additions

Revision ID: 6d5bb791be5a
Revises:
Create Date: 2026-05-29 11:04:48.629041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '6d5bb791be5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # crm_leads is created first because crm_lead_profile references it.
    op.create_table('crm_leads',
    sa.Column('idcrm_lead', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clients_idclients', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('research_type', sa.String(length=100), nullable=True),
    sa.Column('pipeline_status', sa.Enum('Lead', 'Calculation Sent', 'SOW Signed', 'Active Engagement', name='crm_leads_pipeline_status'), server_default='Lead', nullable=False),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('salesperson_iduser', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sow_signed_at', sa.DateTime(), nullable=True),
    sa.Column('engagement_started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['clients_idclients'], ['clients.idclients'], ),
    sa.ForeignKeyConstraint(['salesperson_iduser'], ['users.iduser'], ),
    sa.PrimaryKeyConstraint('idcrm_lead')
    )
    op.create_index('idx_crm_lead_status', 'crm_leads', ['pipeline_status'], unique=False)
    op.create_table('crm_lead_profile',
    sa.Column('idcrm_lead_profile', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clients_idclients', sa.Integer(), nullable=True),
    sa.Column('crm_leads_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['clients_idclients'], ['clients.idclients'], ),
    sa.ForeignKeyConstraint(['crm_leads_id'], ['crm_leads.idcrm_lead'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idcrm_lead_profile'),
    sa.UniqueConstraint('clients_idclients', name='uq_crm_lead_profile_client')
    )
    op.create_table('crm_calculations',
    sa.Column('idcrm_calculation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crm_leads_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('tax_filing_status', sa.String(length=50), nullable=True),
    sa.Column('total_bill', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.iduser'], ),
    sa.ForeignKeyConstraint(['crm_leads_id'], ['crm_leads.idcrm_lead'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idcrm_calculation')
    )
    op.create_table('crm_follow_up_calls',
    sa.Column('idcrm_follow_up_call', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crm_leads_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['crm_leads_id'], ['crm_leads.idcrm_lead'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idcrm_follow_up_call')
    )
    op.create_table('crm_intake_questions',
    sa.Column('idcrm_intake_question', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crm_leads_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['crm_leads_id'], ['crm_leads.idcrm_lead'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idcrm_intake_question')
    )
    op.create_table('crm_calculation_entities',
    sa.Column('idcrm_calculation_entity', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crm_calculations_id', sa.Integer(), nullable=False),
    sa.Column('entities_entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('tax_filing_status', sa.String(length=50), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('estimate_qras', sa.Integer(), nullable=True),
    sa.Column('gross_credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('w2_wages', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('contract_research', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('supplies', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_expenses', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('manager_reviewed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=45), nullable=True),
    sa.Column('total_bill', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['crm_calculations_id'], ['crm_calculations.idcrm_calculation'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entities_entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('idcrm_calculation_entity')
    )
    op.create_table('crm_engagement_billing',
    sa.Column('idcrm_engagement_billing', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engagements_idengagements', sa.Integer(), nullable=False),
    sa.Column('tax_year', mysql.YEAR(), nullable=False),
    sa.Column('billing_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['engagements_idengagements'], ['engagements.idengagements'], ),
    sa.PrimaryKeyConstraint('idcrm_engagement_billing'),
    sa.UniqueConstraint('engagements_idengagements', 'tax_year', name='uq_crm_eng_billing_year')
    )
    op.add_column('engagements', sa.Column('phase', sa.String(length=100), nullable=True))
    op.add_column('engagements', sa.Column('crm_leads_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'engagements', 'crm_leads', ['crm_leads_id'], ['idcrm_lead'])
    op.add_column('people', sa.Column('title', sa.String(length=150), nullable=True))
    op.add_column('people', sa.Column('firm', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'firm')
    op.drop_column('people', 'title')
    op.drop_constraint(None, 'engagements', type_='foreignkey')
    op.drop_column('engagements', 'crm_leads_id')
    op.drop_column('engagements', 'phase')
    op.drop_table('crm_engagement_billing')
    op.drop_table('crm_calculation_entities')
    op.drop_table('crm_intake_questions')
    op.drop_table('crm_follow_up_calls')
    op.drop_table('crm_calculations')
    # crm_lead_profile references crm_leads, so it must drop first.
    op.drop_table('crm_lead_profile')
    op.drop_index('idx_crm_lead_status', table_name='crm_leads')
    op.drop_table('crm_leads')
    # ### end Alembic commands ###
