/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsConfigureRouteImport } from './routes/documents.configure'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as DocumentsReviewEngagementIdRouteImport } from './routes/documents.review.$engagementId'
import { Route as DocumentsEditEngagementIdRouteImport } from './routes/documents.edit.$engagementId'
import { Route as ClientsIdFeasibilityCallRouteImport } from './routes/clients.$id.feasibility-call'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsConfigureRoute = DocumentsConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => DocumentsRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsReviewEngagementIdRoute =
  DocumentsReviewEngagementIdRouteImport.update({
    id: '/review/$engagementId',
    path: '/review/$engagementId',
    getParentRoute: () => DocumentsRoute,
  } as any)
const DocumentsEditEngagementIdRoute =
  DocumentsEditEngagementIdRouteImport.update({
    id: '/edit/$engagementId',
    path: '/edit/$engagementId',
    getParentRoute: () => DocumentsRoute,
  } as any)
const ClientsIdFeasibilityCallRoute =
  ClientsIdFeasibilityCallRouteImport.update({
    id: '/feasibility-call',
    path: '/feasibility-call',
    getParentRoute: () => ClientsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/login': typeof LoginRoute
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/documents/configure': typeof DocumentsConfigureRoute
  '/clients/$id/feasibility-call': typeof ClientsIdFeasibilityCallRoute
  '/documents/edit/$engagementId': typeof DocumentsEditEngagementIdRoute
  '/documents/review/$engagementId': typeof DocumentsReviewEngagementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/login': typeof LoginRoute
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/documents/configure': typeof DocumentsConfigureRoute
  '/clients/$id/feasibility-call': typeof ClientsIdFeasibilityCallRoute
  '/documents/edit/$engagementId': typeof DocumentsEditEngagementIdRoute
  '/documents/review/$engagementId': typeof DocumentsReviewEngagementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/login': typeof LoginRoute
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/documents/configure': typeof DocumentsConfigureRoute
  '/clients/$id/feasibility-call': typeof ClientsIdFeasibilityCallRoute
  '/documents/edit/$engagementId': typeof DocumentsEditEngagementIdRoute
  '/documents/review/$engagementId': typeof DocumentsReviewEngagementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/documents'
    | '/login'
    | '/clients/$id'
    | '/documents/configure'
    | '/clients/$id/feasibility-call'
    | '/documents/edit/$engagementId'
    | '/documents/review/$engagementId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/documents'
    | '/login'
    | '/clients/$id'
    | '/documents/configure'
    | '/clients/$id/feasibility-call'
    | '/documents/edit/$engagementId'
    | '/documents/review/$engagementId'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/documents'
    | '/login'
    | '/clients/$id'
    | '/documents/configure'
    | '/clients/$id/feasibility-call'
    | '/documents/edit/$engagementId'
    | '/documents/review/$engagementId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ClientsIdRoute: typeof ClientsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/configure': {
      id: '/documents/configure'
      path: '/configure'
      fullPath: '/documents/configure'
      preLoaderRoute: typeof DocumentsConfigureRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/review/$engagementId': {
      id: '/documents/review/$engagementId'
      path: '/review/$engagementId'
      fullPath: '/documents/review/$engagementId'
      preLoaderRoute: typeof DocumentsReviewEngagementIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/edit/$engagementId': {
      id: '/documents/edit/$engagementId'
      path: '/edit/$engagementId'
      fullPath: '/documents/edit/$engagementId'
      preLoaderRoute: typeof DocumentsEditEngagementIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/clients/$id/feasibility-call': {
      id: '/clients/$id/feasibility-call'
      path: '/feasibility-call'
      fullPath: '/clients/$id/feasibility-call'
      preLoaderRoute: typeof ClientsIdFeasibilityCallRouteImport
      parentRoute: typeof ClientsIdRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsConfigureRoute: typeof DocumentsConfigureRoute
  DocumentsEditEngagementIdRoute: typeof DocumentsEditEngagementIdRoute
  DocumentsReviewEngagementIdRoute: typeof DocumentsReviewEngagementIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsConfigureRoute: DocumentsConfigureRoute,
  DocumentsEditEngagementIdRoute: DocumentsEditEngagementIdRoute,
  DocumentsReviewEngagementIdRoute: DocumentsReviewEngagementIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface ClientsIdRouteChildren {
  ClientsIdFeasibilityCallRoute: typeof ClientsIdFeasibilityCallRoute
}

const ClientsIdRouteChildren: ClientsIdRouteChildren = {
  ClientsIdFeasibilityCallRoute: ClientsIdFeasibilityCallRoute,
}

const ClientsIdRouteWithChildren = ClientsIdRoute._addFileChildren(
  ClientsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  LoginRoute: LoginRoute,
  ClientsIdRoute: ClientsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
